contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #delly channel"
    url: https://nfcore.slack.com/channels/delly
    about: Discussion about the nf-core/delly pipeline
